version: "3.7"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${COMPOSE_PROJECT_NAME}-mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/wordpress-php:$PHP_TAG
    container_name: "${COMPOSE_PROJECT_NAME}-php"
    environment:
      APP_ENV: dev
      WP_SITEURL: "https://${WP_HOSTNAME}"
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S stonehenge-mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    ## Read instructions at https://wodby.com/docs/stacks/wordpress/local#xdebug
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_IDEKEY: "my-ide"
#      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
#      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS
#      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows
    volumes:
      - ./:/var/www/html:cached
## For XHProf and Xdebug profiler traces
#      - files:/mnt/files
    networks:
      - stonehenge-network
      - default

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: wordpress
      NGINX_SERVER_ROOT: /var/www/html/public
    volumes:
      - ./:/var/www/html:cached
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:${WP_HOSTNAME}"
      traefik.frontend.redirect.entryPoint: https
    networks:
      - stonehenge-network
      - default

networks:
  stonehenge-network:
    external: true

volumes:
  ssh:
    name: stonehenge-ssh
    external: true
