pipeline:

  - name: Install dependencies
    type: command
    command: composer install -n --no-dev
    directory: $APP_ROOT

  - name: Run wp-cli
    type: command
    command: wp --path=/var/www/html/public config
    directory: $APP_ROOT
