pipeline:

  - name: Install dependencies
    type: command
    command: composer install -n --no-dev
    directory: $APP_ROOT

  - name: Copy wp-config.php
    type: command
    command: cp conf/wodby.wp-config.php public/wp-config.php
    directory: $APP_ROOT

  - name: Clean up installation
    type: command
    command: |
      wp --path=/var/www/html/public theme delete twentynineteen twentyseventeen && \
      wp --path=/var/www/html/public plugin delete akismet hello
    directory: $APP_ROOT
